### ISSUE TITLE
Application Context missing LocalEmployeeStorage

### ISSUE THREAD

**Issue by archivedgraf** [cosmiclearn/improve-content#3] opened 2018-12-13 13:47 UTC
Hi,

On the following page:

https://www.cosmiclearn.com/spring/framework_xml_setter.php

The applicationContext sets up the bean employeeStorage for the class EmployeeStorageImpl; however, in the earlier pages the EmployeeStorage interface is implemented in a class called LocalEmployeeStorage.

The code with EmployeeStorageImpl results in a FileNoteFound exception.

**Comment by cosmiclearn** [comment] 2018-12-23 02:07
Thank you for reporting the issue. Apologies, I was on a vacation.

You are right, I created two files in my workspace EmployeeStorageImpl and LocalEmployeeStorage, and this confuses the reader because the project setup has LocalEmployeeStorage.

I have now fixed the tutorial to refer to LocalEmployeeStorage instead.

Many thanks and happy holidays! 
Note: You have to clear the cache or browse incognito to see the changes.

**Comment by cosmiclearn** [comment] 2018-12-25 05:16
Please re-open if you believe the issue is not resolved yet. Thanks for the detailed bug.

**Closed by cosmiclearn** 2018-12-25 05:16 UTC
